CONNECT system/system;

CREATE TABLESPACE SQL3_TBS DATAFILE ‘E:/sql3_tbs.dat’ SIZE 100M 
AUTOEXTEND ON ONLINE;
CREATE TEMPORARY TABLESPACE SQL3_TempTBS TEMPFILE ‘E:/sql3_tbs.dat’ 
SIZE 100M AUTOEXTEND ON;

CREATE USER SQL3 IDENTIFIED BY pwd DEFAULT TABLESPACE SQL3_TBS 
TEMPORARY TABLESPACE SQL3_TempTBS;

GRANT ALL PRIVILEGES TO SQL3;